---
title: Insider London
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Insider London
description: Insider London
baseurl: 
lsi: false
paginate: 10
paginate_path: "/blog/page/:num/"
gems:
- jekyll-paginate
exclude:
- gruntfile.js
- ".gitignore"
- php.ini
- bower.json
- package.json
- node_modules
- bower_components
- wp-content
- ".htaccess"
future: true
markdown: redcarpet
env: prod
imagepath: "/assets/images/"
