---
title: Insider London
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  tours:
    title: Tours
    output: true
    permalink: "/tours/:path/"
  uploads:
    title: Uploads
    output: true
name: Insider London
description: 
baseurl: 
url: http://www.insider-london.co.uk
lsi: false
paginate: 10
paginate_path: "/blog/page/:num/"
gems:
- jekyll-paginate
exclude:
- gruntfile.js
- ".gitignore"
- php.ini
- bower.json
- package.json
- node_modules
- wp-content
- ".htaccess"
future: true
markdown: redcarpet
env: dev
imagepath: "/assets/images/"
