---
title: Insider London
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  tours:
    title: Tours
    output: true
    permalink: "/tours/:path/"
  uploads:
    title: Uploads
    output: true
name: Insider London
description: Insider London
baseurl:
url: "http://www.insider-london.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
lsi: false
paginate: 10
paginate_path: "/blog/page/:num/"
gems:
- jekyll-paginate
exclude:
- gruntfile.js
- ".gitignore"
- php.ini
- bower.json
- package.json
- node_modules
- wp-content
- ".htaccess"
future: true
markdown: redcarpet
env: dev
imagepath: "/assets/images/"
