---
title: Insider London
feed:
  path: blog/atom.xml
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
    permalink: "/authors/:path/"
  posts:
    title: Posts
    output: true
  tours:
    title: Tours
    output: true
    permalink: "/tours/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: authors
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    description:
    author:
    heading:
    categories: blog
- scope:
    path: ''
    type: tours
  values:
    heading:
    description:
    gallery:
    - image:
      caption:
      alt:
    embed:
    order:
- scope:
    path: ''
    type: authors
  values:
    image:
permalink: "/:categories/:title"
social:
  name: Insider London
  links:
  - http://www.facebook.com/insiderlondon
  - https://twitter.com/insiderlondon
  - https://www.instagram.com/insiderlondontours/
twitter:
  username: insiderlondon
name: Insider London
description: At Insider London we offer a variety of alternative guided tours of London
  ideal for tourists, locals, students, school trips, private parties and corporate
  events.
url: https://www.insider-london.co.uk
lang: en_GB
lsi: false
paginate: 10
paginate_path: "/blog/page/:num/"
plugins:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
exclude:
- gruntfile.js
- ".gitignore"
- php.ini
- bower.json
- package.json
- node_modules
- wp-content
- ".htaccess"
- package-lock.json
- Gemfile.lock
- Gemfile
- npm-debug.log
- gulpfile.js
- images
- imgs
future: true
imagepath: "/assets/images/"
compress_html:
  clippings: all
  profile: false
  comments:
  - "<!-- "
  - " -->"
  ignore:
    envs:
    - development
  blanklines: false
