---
title: Insider London
timezone: UTC
collections:
  category:
    title: Category
    output: true
  posts:
    title: Posts
    output: true
  tours:
    title: Tours
    output: true
    permalink: "/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: category
  values:
    layout: category
- scope:
    path: ''
    type: authors
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
<<<<<<< HEAD
    description:
    author:
    excerpt_separator: "<!--more-->"
=======
    description: 
    author: 
>>>>>>> 24d4244222be42044646525329f0515eb9560092
    layout: post
    permalink: "/blog/:title/"
- scope:
    path: ''
    type: tours
  values:
    heading: 
    layout: programme
    script: slick-slider.js
    nav: london
    description: 
    gallery:
    - image: 
      caption: 
      alt: 
    embed: 
    order: 
- scope:
    path: ''
    type: authors
  values:
    image: 
feed:
  path: blog/atom.xml
social:
  name: Insider London
  links:
  - http://www.facebook.com/insiderlondon
  - https://twitter.com/insiderlondon
  - https://www.instagram.com/insiderlondontours/
twitter:
  username: insiderlondon
name: Insider London
description: At Insider London we offer a variety of alternative guided tours of London
  ideal for tourists, locals, students, school trips, private parties and corporate
  events.
url: https://www.insiderlondon.com
lang: en_GB
lsi: false
paginate: 5
paginate_path: "/blog/page/:num/"
gems:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll-admin
exclude:
- gruntfile.js
- ".gitignore"
- php.ini
- bower.json
- package.json
- node_modules
- bower_components
- wp-content
- build
- ".htaccess"
- package-lock.json
- Gemfile.lock
- Gemfile
- npm-debug.log
- gulpfile.js
- images
- imgs
- assets/video
future: true
imagepath: "/assets/images/"
compress_html:
  clippings: all
  profile: false
  comments:
  - "<!-- "
  - " -->"
  ignore:
    envs:
    - development
  blanklines: false
