---
title: Insider London
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  tours:
    title: Tours
    output: true
    permalink: "/tours/:path/"
  uploads:
    title: Uploads
    output: true
  authors:
    title: authors
    output: true
    permalink: "/authors/:path"
defaults:
- scope:
    path: ''
    type: posts
  values:
    description: ''
    author: 
- scope:
    path: ''
    type: tours
  values:
    heading: ''
- scope:
    path: ''
    type: authors
  values:
    image: 
name: Insider London
description: Insider London
baseurl: https://www.insider-london.co.uk
url: https://www.insider-london.co.uk
lsi: false
paginate: 10
paginate_path: "/blog/page/:num/"
gems:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
exclude:
- gruntfile.js
- ".gitignore"
- php.ini
- bower.json
- package.json
- node_modules
- wp-content
- ".htaccess"
future: true
markdown: redcarpet
env: prod
imagepath: "/assets/images/"
