---
title: Insider London
timezone: UTC
collections:
  tours:
    output: true
    permalink: /tours/:path/
name: Insider London
description: Insider London
baseurl:
lsi: false
paginate: 10
paginate_path: "/blog/page/:num/"
gems:
- jekyll-paginate
exclude:
- gruntfile.js
- ".gitignore"
- php.ini
- bower.json
- package.json
- node_modules
- wp-content
- ".htaccess"
future: true
markdown: redcarpet
env: dev
imagepath: "/assets/images/"
