---
title: Insider London
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
    permalink: "/authors/:path"
  posts:
    title: Posts
    output: true
  tours:
    title: Tours
    output: true
    permalink: "/tours/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    description:
    author:
    heading:
- scope:
    path: ''
    type: tours
  values:
    heading:
    description:
- scope:
    path: ''
    type: authors
  values:
    image:
social:
  name: Insider London
  links:
  - http://www.facebook.com/insiderlondon
  - https://twitter.com/#!/insiderlondon
  - https://www.instagram.com/insiderlondontours/
twitter:
  username: insiderlondon
name: Insider London
description: At Insider London we offer a variety of alternative guided tours of London
  ideal for tourists, locals, students, school trips, private parties and corporate
  events.
url: https://www.insider-london.co.uk
lang: en_GB
lsi: false
paginate: 10
paginate_path: "/blog/page/:num/"
gems:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
exclude:
- gruntfile.js
- ".gitignore"
- php.ini
- bower.json
- package.json
- node_modules
- wp-content
- ".htaccess"
- package-lock.json
- Gemfile.lock
- Gemfile
- np-debug.log1
future: true
markdown: redcarpet
env: prod
imagepath: "/assets/images/"
compress_html:
  clippings: all
  comments:
  - "<!-- "
  - " -->"
  ignore:
    envs:
    - local
  blanklines: false
